# general configurations
spring.application.name=scm
server.port=8081

# mysq database configurations
spring.datasource.url=jdbc:mysql://localhost:3306/scm_db
spring.datasource.username=root
spring.datasource.password=rootadmin

# jpa configurations
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# email configuration
